bocadilloproject/bocadillo

CHANGELOG.md
bocadillo/__init__.py
bocadillo/api.py
bocadillo/exceptions.py
bocadillo/media.py
bocadillo/response.py
docs/.vuepress/config.js
docs/guide/api-guides/media.md
docs/guide/api-guides/responses.md
docs/guide/how-to/extra-media-handlers.md
tests/test_media_handlers.py

Add support for media types other than JSON

---

.pre-commit-config.yaml
CONTRIBUTING.md
Pipfile
Pipfile.lock
README.md

Add Black pre-commit hook

---

bocadillo/api.py
bocadillo/compat.py
bocadillo/route.py
tests/test_middleware.py
tests/test_route_hooks.py

Add tests for middleware/hooks method checks and middleware error handling

---

.bumpversion.cfg
CONTRIBUTING.md

This PR updates the contributing guide. I took inspiration from Masonite Core's [CONTRIBUTING.md](https://github.com/MasoniteFramework/core/blob/2.1/CONTRIBUTING.md) to write clearer instructions on how to contribute to Bocadillo, including steps before and after implementing changes.
I'll leave this PR open for some time in case anyone sees anything to add or clarify. :+1:

Improve the CONTRIBUTING guide

---

CHANGELOG.md
bocadillo/error_handlers.py
bocadillo/routing/router.py
bocadillo/view.py
docs/topics/request-handling/routes-url-design.md
tests/test_route_methods.py

Fixes #38 
- Automatically support HEAD if GET is supported
- Update docs and CHANGELOG
Also:
- Print traceback if a 500 error occurs

Map HEAD to GET if supported

---

CONTRIBUTING.md

Just a small change, I didn't think it needed an issue.

Add docs for installing the pre-commit hook

---

bocadillo/api.py
docs/api/api.md
tests/test_asgi_middleware.py

Add support for any ASGI middleware

---

docs/topics/tooling/deployment.md

Add deployment guide

---

.coveragerc
.gitignore
.travis.yml
CONTRIBUTING.md
Pipfile
Pipfile.lock
README.md

Fixes #61 
- Install and configure `coverage.py`
- Integrate Codecov via TravisCI to send coverage reports on PRs

Add codecov

---

CONTRIBUTING.md
Pipfile
Pipfile.lock

Fixed the install command in CONTRIBUTING.md file

---

bocadillo/routing.py
docs/api/api.md
docs/api/routing.md

Remove `methods` arg in `route` docstring

---

docs/guides/http/requests.md

docs/requests: fixed a minor typo and replaced response with request

---

docs/getting-started/snippets/api.py

#108: fixed before_dispatch signature in feature tour snippet

---

Pipfile
Pipfile.lock
bocadillo/websockets.py
docs/api/websockets.md
setup.py

Upgrade to starlette>=0.10

---

CHANGELOG.md
bocadillo/routing.py
tests/test_http_route_wildcards.py

Allow root wildcard pattern

---

CHANGELOG.md
docs/guides/http/routing.md
docs/guides/http/views.md
docs/how-to/tortoise.md

Documentation improvements: wildcard routes, route parameters, view type annotations

---

.gitignore
CHANGELOG.md
Pipfile
Pipfile.lock
README.md
bocadillo/api.py
bocadillo/app_types.py
bocadillo/compat.py
bocadillo/constants.py
bocadillo/errors.py
bocadillo/hooks.py
bocadillo/response.py
bocadillo/routing.py
bocadillo/templates.py
bocadillo/views.py
bocadillo/websockets.py
docs/.vuepress/override.styl
docs/README.md
docs/api/api.md
docs/api/compat.md
docs/api/errors.md
docs/api/middleware.md
docs/api/recipes.md
docs/api/routing.md
docs/api/templates.md
docs/api/websockets.md

Add MyPy to dependencies

---

bocadillo/api.py
bocadillo/app_types.py
bocadillo/compat.py
bocadillo/errors.py
bocadillo/hooks.py
bocadillo/middleware.py
bocadillo/routing.py
bocadillo/views.py
docs/api/api.md
docs/api/compat.md
docs/api/errors.md
docs/api/recipes.md
docs/api/routing.md
docs/api/views.md

Improve type hints in order to make MyPy happy across the code base. Also some docstring improvements along the way.

Various type hints improvements

---

CONTRIBUTING.md
mypy.ini
pylintrc

- Add MyPy config in `mypy.ini`
- Add Pylint config in `pylintrc`
- Add  `Linting` section in `CONTRIBUTING.md`
- Also move instructions to install pre-commit hooks in the better-suited install section of `CONTRIBUTING.md`

Add linting config and instructions

---

.bumpversion.cfg
CHANGELOG.md
CONTRIBUTING.md
bocadillo/__init__.py
docs/getting-started/installation.md
package.json
setup.py

Bump version: 0.11.0 → 0.11.1

---

.bumpversion.cfg
CHANGELOG.md
CONTRIBUTING.md
bocadillo/__init__.py
docs/getting-started/installation.md
package.json
setup.py

Release v0.11.2

---

.bumpversion.cfg
CHANGELOG.md
CONTRIBUTING.md
bocadillo/__init__.py
docs/getting-started/installation.md
package.json
setup.py

Prepare 0.12.0

---

CHANGELOG.md
bocadillo/applications.py
bocadillo/staticfiles.py
docs/guides/http/static-files.md
tests/test_static.py

Whitenoise config

---

CHANGELOG.md
bocadillo/applications.py
tests/test_run.py

Autorefresh static files in debug mode

---

.gitignore
CHANGELOG.md
bocadillo/applications.py
docs/guides/app.md
setup.py
tests/test_run.py

Fixes #186 
- See changes to the changelog.

Add support for uvicorn 0.5.x + debug mode enhancements

---

docs/.vuepress/config.js
docs/guides/websockets/README.md
docs/how-to/socketio.md

Fixes #191 
- Add how-to guide on integrating with socket.io
- Update the WebSocket guide to mention socket.io as a higher-level alternative.

Add socketio integration guide

---

bocadillo/applications.py
bocadillo/compat.py
bocadillo/injection.py
setup.py
tests/test_injection_http_views.py

Refactor built-in app providers

---

bocadillo/testing.py
docs/.vuepress/config.js
docs/guides/http/views.md
docs/guides/injection/README.md
docs/guides/injection/async.md
docs/guides/injection/auto.md
docs/guides/injection/basics.md
docs/guides/injection/builtins.md
docs/guides/injection/factory.md
docs/guides/injection/modularity.md
docs/guides/injection/problem.md
docs/guides/injection/scopes.md
docs/guides/injection/yield.md

Add documentation about providers

---

.travis.yml
Pipfile
bocadillo/applications.py
setup.py
tests/test_sessions.py

Fixes #6
Implement cookie based sessions through Starlette middleware.

Enable support for cookie based sessions. Closes #6.

---

docs/guides/agnostic/templates.md

Fix small typo

---

bocadillo/applications.py

Fix link to WebSocket in App API docs
